[package]
name = "client"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
kairos-delta-tree = {git="https://github.com/jonas089/kairos-delta-tree/"}
crypto = {path="../crypto"}