[package]
name = "risc0-types"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
voting-tree = {path="../voting-tree"}
serde={version="1", features=["derive"]}