[package]
name = "zk-associated"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
voting-tree = {path="../voting-tree"}
crypto = {path="../crypto"}
pgp = "0.13"
serde = {version="1", features=["derive"]}
risc0-types = {path="../risc0-types"}